### ISSUE TITLE
StubJars ignores public static fields

### ISSUE THREAD

**Issue by ItsHarper** [dmssargent/StubJars#1]
Public static fields are useful for stubbing, because they often contain constant values that are useful to use in a program. Commenting out https://github.com/dmssargent/StubJars/blob/develop/src/main/java/davidsar/gent/stubjars/components/JarClass.java#L348 seems to do the trick at first test, so I'm not sure why public static fields were ever filtered out to begin with.

@dmssargent I'd like to make this change for a FIRST Global release, but it appears that the source for the latest version of StubJars (alpha 4) is not available publicly. Can you get the source for alpha 4 published so that I can make this modification on top of that?

**Comment by ItsHarper** [comment]
OK, commenting that out breaks things when you go to compile against the JAR it produces. I'll investigate further.

**Comment by ItsHarper** [comment]
Specifically, it looks to break non-static fields (or at least non-static fields in a static nested class)

**Comment by ItsHarper** [comment]
So that was the issue that alpha 4 fixes. I decompiled alpha 4, and cherry-picked the fix. The problem is that once I did that, removing the check for static fields resulted in broken enum parsing.

For now, I think I'm going to leave this as a feature request, and just edit the single stub class that I actually care about.

**Comment by dmssargent** [comment]
Can you retest with the head of develop?

**Comment by ItsHarper** [comment]
Now it builds, but when you run the resulting OpMode, the static field is returning a blank string. Which I guess would be an OnBotJava issue.
